### ISSUE TITLE
Production workflow

### ISSUE THREAD

**Issue by sergelerner** [pattern-lab/patternlab-php#101]
Hi, i know i tried this before with issue number 82, which was closed, but i struggle to understand the purpose of pattern lab when it come to creating real applications. maybe you can shed some light on this for me. where i work we got exited about this project and decided to use it as a static site generator which was really helpful. now we are at a point where we want to deploy our apps for production. and the only way i see this possible right now is by manually editing the public folder files, copying and pasting and so on.. I can manage that by myself alright, but this way it makes the whole workflow a bit tedious especially if one needs to go back and make changes inside of pattern lab and then go through the whole manual deployment again without some automation tools. This got me thinking maybe we misunderstood the purpose of pattern lab from the first place. 
I'd appreciate to hear more from you regarding this issue. thanks!

**Comment by nkmaurya** [comment]
@dmolsen 
  
HI, please suggest me how to work with pattern lab  and angular js .  Actually I'm building a websites/product  in angular that consumes dynamic data through web Apis.  In this i want to use template/pattern  generated by Pattern lab but i have no idea how to do this. Also I want to use angular routing instead of pattern lab routing. Please provide step by step guide to integrate angular with pattern lab. 
I have downloaded and configure this sample project https://github.com/bmuenzenmeyer/patternlab-node-angular-example, but this doesn't have much to  solve my problem.


Is there any script command to export all templates as html ie. home.html, product-from.html and also is this right way to work with angular & PL?

Thanks
