### ISSUE TITLE
Angular templates conflict with mustache templates

### ISSUE THREAD

**Issue by dmdez** [pattern-lab/patternlab-php#209]
Ran into this issue today when building an Angular app within a mustache template.  Both templating synatax's use the {{ var }} format.  What happens is mustache evaluates those variables and by the time the page loads, they have already been parsed.  So those angular variables disappear.  

In the short term, we were able disable mustache rendering around Angular templates by wrapping with these comments:

<pre>
&lt;!-- {{={{{ }}}=}} -->
  {{ angularVar }}
&lt;!--{{{={{ }}=}}} -->
</pre>

What this does is change the templating syntax to three brackets instead of the standard two.

Not sure if this is a good long term solution, but posted this in case patternlab could do something a little more intuitive to reduce conflicts with Angular apps?

**Comment by jakobloekke** [comment]
@dmolsen Did this feature ever hit master? I can't figure out how I would go about using such a Mustache lambda the way you described in this thread.

**Comment by ahgittin** [comment]
@dmolsen Is there an update on this?  I see the issue is closed but we're hitting the same problem.

We really like Pattern Lab but the syntax conflict between Mustache and Angular is proving an obstacle to our building up the patterns.  We've tried the "set delimiter" option with Mustache to use a non-conflicting item there but no luck.  (Changing the Angular delimiter we think would be too unpleasant for our users.)

Any suggestions you have would be welcome.  We're happy to investigate why Mustache "set delimiter" isn't working as we expected, if you think that would be fruitful.

**Comment by ahgittin** [comment]
aha the "set delimiter" trick works but only on `{{ ` -- it doesn't apply to `{{< otherTemplate >>`` which was the confusion.  easily worked around.

having worked with it more it seems the angular in the mustache seems backwards; we're looking at supporting templates built up with pure-angular
