### ISSUE TITLE
Failing to ignore .svn folders

### ISSUE THREAD

**Issue by collimik** [pattern-lab/patternlab-php#233]
Hi,

I'm using svn to version control a project built with Patternlab-PHP. The watch task gives me trouble, constantly checking and updating files within .svn folders. I've double checked that .svn-pattern is contained in the list of directories to be ignored.

Thanks.

**Comment by devshack** [comment]
This bug is still there and annoying - and was already reported 2 years ago. :(

MacOS X 10.11.3, PHP 5.4 and PHP7, SVN 1.7.20.

Config:

```
// file extensions to ignore when building or watching the source dir, separate with a comma
ie = "scss,DS_Store,less"

// directories and files to ignore when building or watching the source dir, separate with a comma
id = "scss,.svn,.sass-cache"
```

As described above, the watch task is not ignoring .svn directories:

```
php core/builder.php -w
configuring pattern lab...
your site has been generated...
site generation took 2.01396512985 seconds and used 18MB of memory...
watching your site for changes...
.svn/props changed...
.svn/tmp/prop-base changed...
.svn/tmp/props changed...
.svn/props changed...
.svn/tmp/prop-base changed...
.svn/tmp/props changed...
.svn/props changed...
.svn/tmp/prop-base changed...
.svn/tmp/props changed...
.svn/props changed...
^C
```

But the issue doesn't occur on the watch task only, it's a **global** patternlab issue. When building/generating, .svn directories are not ignored as well. All created files look like i.e. this:

/patterns/03-templates-.svn-02-product-detail-page-ets/03-templates-.svn-02-product-detail-page-ets.html?1455879080979

It would be great if this could be fixed. ;)

**Comment by devshack** [comment]
I have found a "solution" for this kind of problem. ;)

Just upgrade the svn repo to v1.7 (or later). In that case, the repo just uses one .svn directory in the project's root and the problem is gone.
