### ISSUE TITLE
a href="..." target="_blank" will not open in a new tab

### ISSUE THREAD

**Issue by brianmccormack** [pattern-lab/patternlab-php#234]
![screen shot 2014-08-21 at 3 34 44 pm](https://cloud.githubusercontent.com/assets/5325124/4002195/4a157368-296a-11e4-9a04-37fa0f99d94c.png)

I've made this change in two places:
public/styleguide/js/postmessage.js & core/styleguide/js/postmessage.js

based on @dmolsen's recommendation:
https://github.com/pattern-lab/patternlab-php/blob/713098396975a372c071e3b5af7632cdf82bf210/core/styleguide/js/postmessage.js#L31-L45

Then I ran generateSite.command and still... nothing :|
https://dl.dropboxusercontent.com/u/8464542/link.mp4

Thanks in advance!

**Comment by jsolis** [comment]
@brianmccormack In addition to the changes you mentioned above, you'll need to also add the *allow-popups* property to the *sandbox* attribute of the iframe#sg-viewport found in the **core/templates/index.mustache** file (which becomes public/index.html) in order for the use of the target attribute on "a" tags to be allowed from within that sandboxed iframe:

`<iframe id="sg-viewport" sandbox="allow-same-origin allow-scripts allow-popups"></iframe>`

**Comment by brianmccormack** [comment]
@jsolis - it works!!! Thanks!

**Comment by lostsatellites** [comment]
@jsolis That worked to have links open in the iframe (using target="_blank"), but I can't get anything to open in a new tab/window. Also, for some links I'm getting this error: "Refused to display 'https://twitter.com/dmolsen' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'." when launched from a link like this <a href="http://twitter.com/dmolsen" target="_blank">Dave Olsen</a>

**Comment by dmolsen** [comment]
@lostsatellites-

I'm pretty sure the `X-Frame-Options` issue is because of your server and
not because of Pattern Lab. The header prevents "frame busting." If it's
enabled then I doubt there's a good workaround. Sorry.

On Mon, May 18, 2015 at 10:01 AM, lostsatellites <notifications@github.com>
wrote:

> @jsolis <https://github.com/jsolis> That worked to have links open in the
> iframe (using target="_blank"), but I can't get anything to open in a new
> tab/window. Also, for some links I'm getting this error: "Refused to
> display 'https://twitter.com/dmolsen' in a frame because it set
> 'X-Frame-Options' to 'SAMEORIGIN'." when launched from a link like this Dave
> Olsen <http://twitter.com/dmolsen>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pattern-lab/patternlab-php/issues/234#issuecomment-103069541>
> .
>



-- 

http://dmolsen.com

**Comment by jsolis** [comment]
@lostsatellites - @dmolsen is correct.  See this:
https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

> The X-Frame-Options HTTP response header can be used to indicate whether or not a browser should be allowed to render a page in a &lt;frame&gt;, &lt;iframe&gt; or &lt;object&gt; . Sites can use this to avoid clickjacking attacks, by ensuring that their content is not embedded into other sites.

And if you inspect the document response from twitter, you can see they are sending that header:
`x-frame-options:SAMEORIGIN`

**Comment by dmolsen** [comment]
@jsolis -

Thanks for providing more detail on that.

**Comment by lostsatellites** [comment]
Thanks to both of you, that's helpful info.
