### ISSUE TITLE
Wrench BadRequestException: No origin header

### ISSUE THREAD

**Issue by felippenardi** [pattern-lab/patternlab-php#255]
Hi there,

I'm trying to run the builder command with the watch and auto reload server with this command:
```
docker run -t --rm --name my-running-script -v "$(pwd)":/usr/src/myapp -w /usr/src/myapp -p 7007:8002 php:5.6-cli php core/builder.php -w -r
```
It basically gets a PHP Docker to run my command. It seems to work, the output is:
```
configuring pattern lab...
your site has been generated...
site generation took 0.27731108665466 seconds and used 4MB of memory...
starting page auto-reload...
watching your site for changes...
info: Server initialized
```

 But then when I try to connect to my site on the browser, I see just a blank page and the only error is a 404 for the favicon.

On the server side, I get this output:

```
info: Wrench\ConnectionManager: Wrench\Connection: 187.67.9.15:65245 (2762c0c7d40637e8455ad4b9fdad42c0065a859da273d713eb5e7d6e73bb2177424d01a41f95f285c3190f16fc5ab5f23c411b58cfacad87522f5e67be297a4b): Connected
warning: Wrench\ConnectionManager: Error on client socket: exception 'Wrench\Exception\BadRequestException' with message 'No origin header' in /usr/src/myapp/core/lib/Wrench/Protocol/Protocol.php:455  Stack trace:#0 /usr/src/myapp/core/lib/Wrench/Connection.php(227): Wrench\Protocol\Protocol->validateRequestHandshake('GET / HTTP/1.1\r...')#1 /usr/src/myapp/core/lib/Wrench/Connection.php(210): Wrench\Connection->handshake('GET / HTTP/1.1\r...')#2 /usr/src/myapp/core/lib/Wrench/Connection.php(403): Wrench\Connection->onData('GET / HTTP/1.1\r...')#3 /usr/src/myapp/core/lib/Wrench/ConnectionManager.php(245): Wrench\Connection->process()#4 /usr/src/myapp/core/lib/Wrench/ConnectionManager.php(172): Wrench\ConnectionManager->processClientSocket(Resource id #146)#5 /usr/src/myapp/core/lib/Wrench/Server.php(201): Wrench\ConnectionManager->selectAndProcess()#6 /usr/src/myapp/core/autoReloadServer.php(45): Wrench\Server->run()#7 {main}
```

**Comment by dmolsen** [comment]
@felippenardi -

I'll be honest, I'm not in a good position to debug this nor am I really familiar with the Wrench stuff. I just plugged it together and stuff seemed to work. Sorry.

**Comment by linoleumtile** [comment]
I see this is closed, but I am also having the same problem with files when trying to use the servers in core/scripts. Tried it with my old files, as well as a fresh new clone of pattern-lab/patternlab-php and I keep seeing 400 error when trying to load the page, and wrench related errors in the terminal.

**Comment by guile** [comment]
Hey, im having this same issue. I tried moving my folders to default web server location but that didn't help. @dmolsen @felippenardi @linoleumtile 
AFAIK, when starting the Wrench server, the Origin field in the header is sent blank, which is why it is throwing a BadRequestException (why not an InvalidOriginException instead?).
Any leads to fixing this?

**Comment by linoleumtile** [comment]
@guile I've been just serving patternlab>public with jekyll and running the generate script when I need to. Not a fix, but it gets the job done for me.

**Comment by lrobeson** [comment]
This was happening with my Grunt setup and I think it's because I had a Shell task running `'php core/builder.php -wr'` after Sass changes but `'php core/builder.php -wr'` was _already_ running because it was called in my default (concurrent) task. I was making it too complicated.

Now I just have a Sass watch task that runs Compass and I let Pattern Lab's native watch task (`'php core/builder.php -wr'`) handle the rest. So maybe check if that's the case with your particular setup. I can share my Grunt setup if that would help anyone.
