### ISSUE TITLE
Pseudo patterns don't work in view all

### ISSUE THREAD

**Issue by u982744** [pattern-lab/patternlab-php#272]
I have used a number of pseudo patterns to show various states of the same pattern with booleans. This works fine except all the pseudo patterns show as blank on the view all pages.

**Comment by dmolsen** [comment]
Thanks for reporting this. I'll take a look at it.

**Comment by u982744** [comment]
Any luck figuring this one out?

**Comment by dmolsen** [comment]
Nothing is jumping out but I can't say I've debugged it in detail. I've been focused on trying to clean up PL2 so it's a little tough jumping back into the old code.

**Comment by u982744** [comment]
Fair enough. I might have a look and see if I can fix myself and do a pull request. Having no knowledge of the code I'm not sure how much luck I'll have though!

**Comment by lostsatellites** [comment]
Any updates on this? Has been happening to me from the get-go.

**Comment by wonkeythemonkey** [comment]
I've had (I think) a similar issue. In particular, if my pseudo-pattern is modifying a value that is multiple levels deep in _data.json, the entire parent object is replaced instead of just the chosen attribute.

For example, if this is the code in _data.json…
```
{
    "callout" : {
            "headline" :  "Sample headline",
            "content" : "Sample content."
    }
}
```

…and I have a partial called `callout-block.mustache`, I can put this code into `callout-block.json` and it will work fine:

```
{
    "callout" : {
            "content" : "New content."
    }
}
```

However, if I try to create a pseudo-pattern using a file called `callout-block~new-content.json`, the same code will give me a blank pattern. Adding the `"headline"` attribute back into the file will cause it to work again, but it requires specifying text for this particular pseudo-pattern.

It seems that in pseudo-patterns with multiple levels of depth, the entire object (in this case `"callout"`) is replaced instead of just the listed attributes.

**Comment by rasenplanscher** [comment]
I have run into this today, with v0.7.12, in the same way as @wonkeythemonkey. I have also noticed that if I override a 4-items array with a 2-items array, my context will have the two overrides plus the last two original items. That leads to a rather simple obdeduction: patternlab builds the initial context from`_data.json`, then deep-merges the partial-specific data object, then shallow-merges the pseudo-pattern-specific data object. Therefore, it should be as simple as having the deep-merge from the pattern applied for the pseudo pattern as well.
