### ISSUE TITLE
PatternLab in a multi-client/multi-site setup

### ISSUE THREAD

**Issue by mikkelbreum** [pattern-lab/patternlab-php#273]
Hi there

My team is starting a new project where we will be developing 30+ new large websites for individual subsidiary companies all belonging to the same holding company.

Along with the web sites we'll be developing living style guides, one for each company.
We're looking into using PatternLab for this, but we're not sure how to best approach the setup.

We obviously want to apply a DRY principle, and maintain as little duplicate code as possible.

I've been reading about PatternLab 0.8/2.0 and it's new architecture for facilitating a multi-site setup, but I'm not sure exactly how to do this, or if it is ready yet?

We are picturing the setup something like this:

-  We'll maintain a master pattern library that contains all the basic elements: **atoms**, **molecules**, **organisms** found across all the sites (the mother company and all it's subsidiaries). Here we'll apply some generic styling.
- There will also need to be a separate library for each specific client site, where the visual design is specific to the particular client/brand, and where we include the **templates** and **pages** for the given site.
-  When we need to add an element to a specific site we'll first add it to this master library, and then override aspects of it in the pattern library of the relevant client(s).
- We'll need to way to include/exclude the elements we need/don't need from the master labrary for each sub library.
- We'll need a simple way to 'override' the default styling of elements (probably mostly on the atomic level) for each sub-library. Ideally so that anything not specifically overridden will be inherited from the master library.

is it possible to do something like this with PatternLab?

**Comment by bradfrost** [comment]
Hey @mikkelbreum,
Thanks for sharing your upcoming project! Sounds like a pretty amazing one.

Regarding your questions, I'd have a few suggestions:
- Pattern Lab allows you to include/exclude folders, so you can easily make a pattern lab containing only atoms, molecules, and organisms.
- Without seeing the individual site structure, it's hard to make a call on how to architect the setup. If you're only making variations to core templates, you could include all the variations under one roof doing something like `<body class="{{ bodyClass }}">`, which would allow you to apply different styles based on the styles.
- Alternately, you could set up individual Pattern Lab instances that would import the patterns from the "master" Pattern Lab containing the atoms, molecules, and organisms. You could use something like [Grunt copy](https://github.com/gruntjs/grunt-contrib-copy) to automatically copy the shared atoms, molecules, and organisms over to each individual Pattern Lab. 
- Because the dependencies of the new version of Pattern Lab are managed through composer, having multiple instances of Pattern Lab running shouldn't be hard to maintain.

Hope this helps a little, and good luck!

**Comment by mikkelbreum** [comment]
Hi @bradfrost thanks a lot for the feedback. I'll start setting up a hackerLab here, and get to know PatternLab and the whole mental model, then it will probably become more clear how to best set the whole thing up in terms of architecture. I'll try to share the process in a blog, will keep you posted in this thread with a link once I get that far. In case ou want to close this to keep the issue list clean I'll just mail you and you can add it manually.

On a side note: We installed the [Daisy Vagrant](https://github.com/HBRGTech/daisy), it's a very nice box for collaborating on a PatternLab projects (and I love to keep all my projects sand-boxed from my Mac).

**Comment by dmolsen** [comment]
@mikkelbreum -

While Pattern Lab 2 isn't quite ready for prime-time I wanted to chime in with how it'd answer your questions. PL2 is all about modularity. While quasi-multi-site support is in PL2 it doesn't support sharing assets between "sites." I think Composer, which PL2 requires, provides the basis for a better answer when it comes to multi-site support. Two Composer-driven features of PL2 that could help you out are Editions and StarterKits.

Editions are the thin shell of a Pattern Lab project and define its general properties. These properties include basic configuration information, the PatternEngine, and extra plug-ins. I foresee agencies having a custom Edition that serves as the base from which they build all their projects. You can see/play with either the [Mustache](https://github.com/pattern-lab/edition-php-development) or [Twig](https://github.com/pattern-lab/edition-php-twig-development) Development Editions. [Composer's create-project option](https://getcomposer.org/doc/03-cli.md#create-project) is the secret sauce to making Editions tick. We use `create-project` a lot at my workplace.

StarterKits are version-able bundles of  the `source/` directory from PL1. You can see how we've broken out the demo into separate StarterKits for [Mustache](https://github.com/pattern-lab/starterkit-mustache-demo) and [Twig]( https://github.com/pattern-lab/starterkit-twig-demo). When you install a StarterKit, Composer copies everything from the StarterKit's `dist/` directory into the project's `source/` directory. This is [controlled by the configuration for the StarterKit](https://github.com/pattern-lab/starterkit-twig-demo/blob/2be09a08f378ebc5f3991e41c5b38746b6da1449/composer.json#L29-L33) and there's a lot of flexibility when setting it up. The default StyleguideKit [provides a good example of this type of specificity](https://github.com/pattern-lab/styleguidekit-assets-default/blob/77f7a977665ca270de5e1c4292eadc33a5c136a7/composer.json#L28-L40) when copying files. This flexibility would even allow for the mixing and matching of StarterKits.

So with that lengthy tangent into Pattern Lab 2 components out of the way the following is how I could see them answering your questions. This is what I'd set-up for your agency:

1. the "master" StarterKit that contains your core assets. In this case it'd contain atoms, molecules, and organisms.
2. a base Edition that contains a common project configuration, choice of Pattern Engine, the "master" StarterKit as a dependency, and any extras. These include things like `package.json` and a Gulp file.

The workflow for an agency project might look like:

1. A developer or designer uses Composer's `create-project` feature to copy the agency's base Edition. It automatically installs the "master" StarterKit. The install becomes the base for a subsidiary-related project. It can be added to a repository for checkout/use/modification.
2. The developer/designer builds out the templates/pages and custom CSS in the subsidiary-related project.
3. When the agency updates the "master" StarterKit each subsidiary project runs `composer update agency-name/starterkit-master` to get the latest patterns. **Note:** you can use [private repositories as package sources](https://getcomposer.org/doc/05-repositories.md) instead of relying on [Packagist](http://packagist.org). No need to expose your projects to the world.

I haven't played w/ Daisy Vagrant so can't comment on that part of the workflow. That said, I think this answers the bulk of your questions. What it doesn't answer is how to cull patterns you may not need in a subsidiary-related project. A plug-in would be a good answer. The plug-in would run after the the install or update of the "master" StarterKit. Based on a config the plugin could delete patterns after the fact. PL2 has an events dispatcher that would make this trivial. I don't currently fire an event after install/update of plug-ins though.

Pros:

* this offers a nice separation of bits. The "master" StarterKit  will be DRY at least.
* using semantic versioning for your "master" StarterKit can ensure subsidiary projects don't break accidentally
* each subsidiary project is under its own version/access control

Cons:

* there will be an install of PL for each subsidiary project. To update PL someone will need to run `composer update pattern-lab/core` for each one. I don't expect a ton of releases though.
* modifications to files installed by the "master" StarterKit would be overwritten when it's updated. 

That was a whole lot of text but I hope it helps as you try to figure out if PL1 and PL2 are right for your team. Since it seems that @bradfrost addressed the initial issue I'm going to close this up. If you have feedback on what I've shared please feel free to continue the thread. It'd be great to get another perspective.

**Comment by mikkelbreum** [comment]
Thank you so much for a detailed and engaged answer @dmolsen We're really exited to start using PatternLab here in my team. the whole mental model of Atomic Design has also been a huge help to us as we communicate with customers and across the departments in the company. Have you considered running a kickstarter to support the development of PatternLab? It's of high value to us, we would certainly support such a project.

**Comment by dmolsen** [comment]
@mikkelbreum -

Really happy to hear that Atomic Design has helped the team :) While I haven't looked at KickStarter I have considered a tip jar. It'd be easier to carve out dedicated time if I could show there was a financial reward ;) Frankly, my greatest motivator is engaged users. Questions like yours are what make me want to push the project more.

**Comment by mikkelbreum** [comment]
Yeah helping others is a big motivator :) I come from a background of open source hacking and I know what you mean. And I'm sure the reason open source solutions are often superior to their commercial counterparts is just that they are driven by civic rather than monetary motivation. But sometimes I see valuable open source projects go stale, because developers can't dedicate enough time in competition with the paid jobs they need to prioritize. At the same time I know that corporate entities don't mind paying $100k+ a year in license fees, often for inferior systems that has open source counterparts. So this has made me think that more open source projects should approach the 'support us to ensure continuous development' model. Here kickstarter could be one way to go. In Sweden, where I work, I know PatternLab is a valuable asset used in a lot of projects - for very large companies.

**Comment by nmeirik** [comment]
@mikkelbreum If you have a few minutes, I would love to hear how you went about solving this. I represent an agency in Norway with pretty much the exact same challenge as yourself, and I'm currently looking for the best solution available to us as of now.

Allthough the PL2 features Editions, StarterKits and Twig support would fit us perfectly, judging from the commit history progress appears to have been halted for the past six months. Which route did you decide to go for your own team, and how happy are you with the outcome?

**Comment by IrvBriscoe** [comment]
Same here, @mikkelbreum are you available for a quick review/discussion on how you were able to get this solved?
