### ISSUE TITLE
Core style isn't re-built / cloned in to public.

### ISSUE THREAD

**Issue by LucPestille** [pattern-lab/patternlab-php#274]
I've been re-styling the global header and the dropdown menus (outside of the iframe where the patterns sit) to better match company branding, adding in a logo and such, and have come across a problem (feature?).

The stylesheet used for the header, located in /*core*/styleguide/css/styleguide.(s)css is not automatically copied across in to /*public*/styleguide/css/styleguide.(s)css when the site is built, either from scratch, or using the watcher. This means having to manually copy the generated .css across every time it's built, in order to see progress, which, as you can imagine, gets boring quickly.

It took me far to long to dig down to figure out which .scss file was being used and what was/wasn't happening. 

It would be useful if;
- The styleguide.css (and/or the entire /styleguide folder) was tracked and copied in to /public as the site was re-built.
- The styleguide.scss was *not* copied across in to /public, so as to eliminate confusion.

Make sense? Hopefully I've actually understood it all and haven't made a n00b mistake...

**Comment by dmolsen** [comment]
@LucPestille -

You should be able to edit files in `public/styleguide` all you want without having to worry about things getting overwritten. `core/styleguide` is only ever meant to be copied once so it's never touched again by PL. Once satisfied with your changes I guess you can then copy back to `core/` since it seems you want the changes tracked for others. Obviously, run a small test but it should work.

I've spun out the `styleguide/` assets into their own feature called StyleguideKits in PL2 so hopefully this kind of thing is at least a little bit cleaner in the future. In that scenario the Sass files do stay appropriately tucked away ;) You can see an example with the [default StyleguideKit assets](https://github.com/pattern-lab/styleguidekit-assets-default).

Let me know if editing `public/styleguide` directly works for you.
