### ISSUE TITLE
Is it possible to have dynamic bodyClass?

### ISSUE THREAD

**Issue by FStop** [pattern-lab/patternlab-php#278]
What I'm looking for is a body class that's unique to each individual pattern that doesn't require me creating a new JSON file for each one.

So when I'm looking at `/00-atoms/03-forms/02-checkbox` for example, it would be great if the body class could include `atoms-forms-checkbox` or something like that.

The reason I'd like to see this is that when displaying some Atoms and Molecules it would be nice to have some extra padding on the body or container element. But if I include markup in the pattern itself that that is included when the pattern is included in another. Does that make sense?

**Comment by dmolsen** [comment]
@FStop -

So you just want an attribute that is something like `currentPattern` or similar? So you could do `<body class="{{ currentPattern }}">`?

**Comment by bradfrost** [comment]
Hey @FStop,
You can also add custom styles by modifying `styleguide-specific.(s)css`. Each pattern in the list view has a unique ID attached to it, so you can target specific patterns in the CSS.

**Comment by FStop** [comment]
@dmolsen I tried adding `<body class="{{ currentPattern }}">` in `source/_patterns/00-atoms/00-meta/_00-head.mustache`, but no output for `{{ currentPattern }}` when I view an individual pattern, say patternlab.dev/?p=atoms-colors.

**Comment by FStop** [comment]
@bradfrost thanks for pointing that out. It's helpful for the list view, and I was hoping there was something similar for individual view.

**Comment by dmolsen** [comment]
I apologize. I was asking if that was a feature you'd like to see and if it'd work for you that way. Hasn't been implemented yet :)

**Comment by FStop** [comment]
Oh :+1: 

Then yes, that would be pretty awesome.

**Comment by iansoper** [comment]
If you use `{% patternPartial %}` it will output the pattern name (like the url).

**Comment by FStop** [comment]
@iansoper `<body class="{% patternPartial %}">` outputs that literally, no replacement, for me.

**Comment by dmolsen** [comment]
Ian-

That looks suspiciously like Twig. This repo is still Pattern Lab 1.0 and Mustache-based. Just want to double-check so others checking on this know the appropriate environment that an answer works with. 

Pattern Lab 2 and its various options are going to be interesting to support ;)

**Comment by umesh-velir** [comment]
@FStop One of my colleagues was running into the same issue. We needed to have spacing around all the patterns except for templates and pages. Using {{bodyClass}} was great but having to add that for each and every partial/pattern did not sound efficient. So he tried the other way around - defined the bodyClass in global data and overwrote it in page level (since there were few pages). I was still not happy and thought there must be another way. I noticed that patternlab outputs JSON object in the footer for each pattern/partial. So I tried to utilize that data to add class or new attribute on the body tag, something like this:
`<script> 
var data = JSON.parse($("#sg-pattern-data-footer").html());
if(data.patternType !== 'templates' || data.patternType !== 'pages') {
	$('body').attr('data-class', 'partial-not-compact');
}
</script>`

This way we can have global style for all the patterns minus the templates and pages. And we can use bodyClass to override that for specific pattern if need be.

Hope this helps!

Thanks!
Umesh
