### ISSUE TITLE
Instructions to prevent Javascript firing twice

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#294]
when adding javascript code within a mustache file it fires events twice, I know this has been discussed here https://github.com/pattern-lab/patternlab-php/issues/87 but no specific instructions are given? Could someone please give detailed instructions, on how to fix this?

 $(document).on('click ', '.prev', function(e){
                  e.preventDefault();   
                  var slider = $('.main-slider .cycle-slideshow');    
                  slider.cycle('prev');
                  $('.main-slider .tabs').addClass("finished");                 
                  $('.main-slider .cycle-slideshow .progress-wrapper').hide();
                  
            });

Thanks.

**Comment by dmolsen** [comment]
@Machinas -

The fix for this issue was on my end. At least in #87 it was. If a pattern had JavaScript and it was loaded for the "code panel" modal the JS would load a second time. It _should_ be escaped now so that shouldn't create the mysterious second firing. Alternatively, if you include a single pattern with JS one or more times that may also cause similar issues.

**Comment by Machinas** [comment]
HI @dmolsen I added the script within the mustache file of the pattern should this be placed somewhere else?
