### ISSUE TITLE
Clicking `href`-less anchor results in attempt to load null pattern.

### ISSUE THREAD

**Issue by uglymunky** [pattern-lab/patternlab-php#299]
Using Foundation, I have an anchor element with no href which is meant to close the [off-canvas](http://foundation.zurb.com/docs/components/offcanvas.html) side-nav.  However, whenever it is clicked it also tries to load a pattern named `null` from my current path resulting in a 404.

Not sure how intentional this behavior is, but it would be great if anchors with no hrefs (` <a></a>`) did not attempt to load a pattern when clicked.

**Comment by dmolsen** [comment]
@uglymunky -

Would you mind doing a little legwork for me, please? I'm not in a position to debug today but if you have a minute you can give an idea a try and see if it works. In `public/styleguide/js/postmessage.js` fix [lines 35-37](https://github.com/pattern-lab/patternlab-php/blob/7e65772336109c6966d521d3793b84ab51fa7156/core/styleguide/js/postmessage.js#L35-L37)

Instead of `if (href != "#") {` it should probably be `if ((href !== null) && (href !== "#")) {`.

Let me know if that works for you.

**Comment by uglymunky** [comment]
That did, indeed fix it. I'm embarrassed to admit how long I looked for the code that was doing that last night...thanks for pointing me in the right direction!

Also, I wasn't sure if it made sense to account cases where the href might be any of the other falsy values so I went with `(href && href !== "#")`.

Let me know if you'd like a pull request.

On a related topic.  Are there any plans to turn patternLab into some kind of site generator?  Seems it could make pulling down changes + making upstream changes much easier.
