### ISSUE TITLE
Unescaped HTML & File Naming Convention

### ISSUE THREAD

**Issue by zarahzachz** [pattern-lab/patternlab-php#318]
I might have found a bug in PL when working with unescaped HTML in files with a 3-digit prefix - particular for files beginning with double-zero.

I'm working on a large project using a lot of elements. To maintain order, we've implemented a 3-digit prefix rather than the 2-digit one present in documentation. So **01-ordered.mustache** becomes **001-ordered.mustache** in our project.

What I've discovered is using triple curly brackets seems to break in PL files prefaced with 2+ zeroes and works fine on other 3-digit files. I've tested this theory on my teammates computers and this seems to be the case in their environments as well.

Has anyone else come across this issue? For a quick workaround on our end, we're just replacing all double-0's with double-9's.

**Comment by bradfrost** [comment]
I believe @dmolsen hard-coded the two-digit convention in there to organize the files, so I don't think three digit prefixes were anticipated. It's also worth stating the numeric prefixes aren't a requirement; I just used them in my projects to keep the ordering the way I wanted. I've since moved away from prefixing unless there's something I know I want at the top.
