### ISSUE TITLE
Configuration of the /public output 

### ISSUE THREAD

**Issue by mstretz** [pattern-lab/patternlab-php#319]
Hi,
I'm quite new to PatternLab. So perhaps there is any reason why this can't work, which I don't see right now.
is there any way to determine the structure of the /public folder?
For Example instead of:

/public/patterns
- 04-pages-00-homepage/04-pages-00-homepage.html
- 04-pages-01-blog/04-pages-01-blog.html
- 04-pages-02-article/04-pages-02-article.html

I want to retrieve something like that:

/public/patterns
- 04-pages/00-homepage.html
- 04-pages/01-blog.html
- 04-pages/02-article.html

The more generic it can be configured the merrier.

Thanks for Help!

**Comment by simonvart** [comment]
Hi,

Why would like to determine the structure of the /public folder ? 

This is the working directory for the "engine" of PatternLab to run, we're just suppose to work inside /source

What is your need precisely ?

**Comment by mstretz** [comment]
Hi,

Thanks for the answer.

I need all generated html-files in one directory, if the corresponding mustache-files are in one directory, too.

I have got two mustage-files:
/source/04-pages/00-homepage.mustache
/source/04-pages/01-blog.mustache

This generates into two different directories:
/public/04-pages-00-homepage/04-pages-00-homepage.html
/public/04-pages-01-blog/04-pages-01-blog.html

But I want to get both html-files in the same directory. Something like that:
/public/04-pages/00-homepage.html
/public/04-pages/01-blog.html

How can I get PatternLab to put mustaches from one directory into the same directory? Is there a config? Is there any name-convention? Or won't this work?

Thanks for Feedback!

**Comment by simonvart** [comment]
Hi,

I don't know since I don't even look how things are organized inside /public

As I see it, each pattern corresponds to a folder, since it contains : the
generated HTML fragment, the generated escaped HTML fragment (for display)
and the mustache code (for display too).

So it is closely tied to the frontend.

I guess you could change the rules used in the
/core/lib/Patternlab/Generator.php file (function generatePatternFile()),
but I suppose it will require to refactor some of the PatternLab frontend,
and represents a good deal of work and tests - for I purpose I cannot
clearly understand.

My suggestion would be : don't do it as it probably don't worth it :)

It would maybe be easier to use another tool to search, find and copy each
.html files [not:escaped.html] into another file structure, for your
particular use.

Regards
Simon


2015-09-18 7:51 GMT+02:00 mstretz <notifications@github.com>:
