### ISSUE TITLE
Changing the theme

### ISSUE THREAD

**Issue by velvetlicious** [pattern-lab/patternlab-php#321]
Hi there!
I'm new to patternlab and I'm having trouble understanding how / where can I change or modify the theme of the styleguide. I'd like to create a new theme that is more complimentary of my brand.

Any help will be appreciated.

**Comment by bradfrost** [comment]
Hey there @velvetlicious,
You can edit the Pattern Lab styles by editing `/public/styleguide/css/styleguide.scss` and `/public/styleguide/css/styleguide-specific.scss`

**Comment by vlrprbttst** [comment]
i was about to ask the same question. i was confused because you have these same files in the `core/styleguide/css/` as well but.. what's the difference and why? which one should I edit?

I'm experimenting with patternlab and what i did before reading this issue is modify `core/styleguide/css/styleguide-specific.scss` which compiles to `core/styleguide/css/styleguide-specific.scss` i then copy the resulting css with `grunt-contrib-copy` to `public/styleguide/css/` and regenerate the site with `grunt-shell` running the command `command: "php core/builder.php -g -c"`

is there anything wrong with this (except it's a bit more complicated then going with public/ directly)?
thanks guys!
