### ISSUE TITLE
search box right border missing in style guide

### ISSUE THREAD

**Issue by jsegal205** [pattern-lab/patternlab-php#339]
The search box in the style guide is missing the right border.

This happens in: 
Chrome Version 48.0.2564.97 (64-bit) Mac
Firefox v44
Safari Version 9.0.2 (11601.3.9)

http://demo.patternlab.io/patterns/01-molecules-04-forms-00-search/01-molecules-04-forms-00-search.html
http://demo.patternlab.io/?p=organisms-header

<img width="401" alt="screen shot 2016-01-28 at 8 58 03 am" src="https://cloud.githubusercontent.com/assets/1733595/12647963/51e7f7a2-c59d-11e5-8d4c-b25efd1c6fa6.png">

**Comment by bradfrost** [comment]
@jsegal205 Hey there. Thanks for pointing this out. While it wasn't intentional originally, we're leaving it in there to underscore the idea that the styles _within_ Pattern Lab aren't meant to be used. Whatever exists inside of Pattern Lab should be bulldozed and replaced with your own custom styles.
