### ISSUE TITLE
Pattern Parameters - possibility of using variables instead of just strings 

### ISSUE THREAD

**Issue by Pepino710** [pattern-lab/patternlab-php#358]
Hi there!
Let's say that there are 2 organisms and each of them would like to include the same atoms - h3.mustache, p.mustache. Both atoms takes values from data.json - variables 'h3-title' and 'para', respectively. So that means that both organisms (boxes or blocks) are presented with the same data.

Of course, we can use {{> atoms-p(para: “new string”) }} within organism itself, but values are hard-coded in the template. 
It would be much more flexible to use  {{> atoms-p(para: “ {{another-variable-from-data.json}} ”) }}. Now, we can use for each organism different general data from data.json/listitems.json, and in the upper level of templates or pages override it with custom.data.json for each box.

Thanks.
Josef

**Comment by bradfrost** [comment]
Hey @Pepino710,
Currently Pattern Lab swaps out data at the page level. So if you had two instances of an organism that you wanted to feed different data, you would do:

`````
{{# instance1 }}
{{> organism-card }}
{{/ instance 1}}

{{# instance2 }}
{{> organism-card }}
{{/ instance 2}}
````
Then in your page-specific data you can do the following:

`````
"instance1" : {
  "title": "The first title",
  "para" "This is the first paragraph."
}, 
"instance2" : {
  "title": "The second title",
  "para" "This is the second paragraph."
}
`````

I believe there is a limitation with how pattern parameters work which is why you can't include a variable inside the pattern parameter. But I can't really speak to that as @dmolsen is the one that knows how that all works.
