### ISSUE TITLE
I have a strange issue while invoking npm run local-dev

### ISSUE THREAD

**Issue by dhayalanms** [pattern-lab/patternlab-php#359]
After installing the patter-lab php in local using npm install , I have tried to invoke grunt , but for some reasons its getting exit in the line with message showing that "Please make sure that Pattern Lab can write a new config to config/."  The line points to copying the config.ini.default into config,ini. The copying is getting failed. I have fixed it temporarily by harding the config ini path.

The line number 25  and 27 in PatterLab/Configure.php 

$this->userConfigPath = __DIR__."/../../../config/config.ini";
$this->plConfigPath   = __DIR__."/../../config/config.ini.default";

There error shows a message as (When i remove the @ from the copy function) file not found.

**Comment by dmolsen** [comment]
@dhayalanms -

Can you let me know what package you used with `npm install` to install PL/PHP? That's not an official method of installing PL/PHP so it's difficult to troubleshoot the problem. The paths in PL/PHP are expecting an install via Composer and not NPM so that would most likely be the cause of the issue.
